SCREEN 13

PAINT (0, 0), 15

DRAW "C0"

DRAW "                       BM104,45                       "
DRAW "                U6M+2,-6E2U2E3RE2M+7,-3               "
DRAW "         M+11,-3M+3,-2R7ER19FR3FRM+5,2R5M+3,1         "
DRAW "       M+10,5FRF4RF3M+4,17M+1,4M-3,+6GM-1,+7D3G2      "
DRAW "        D5M-2,+3GD14GD7G3M-2,+1M+3,-11U3M-2,-13U9     "
DRAW "       M-2,-5UHM-2,-6H2M-5,-2M-3,-1L11GL3M-7,-3LH     "
DRAW "      M-6,-1G3FDM-5,-2L5M-7,+1M-3,+1M-2,+4DM-2,+5     "
DRAW "  M+2,+1G2DRDGDFM-7,+4D9GD6M+2,7M+8,16DFD10FD2M+4,8F  "
DRAW "   DF5RF5RF3R3FR14ER2E9R7    M-4,+7M-5,+10M-8,+22DU   "
DRAW "   M-3,-7M-3,-1                          M-6,-3H11L   "
DRAW "    H8UH5UH3UH2                           M-2,-4H2U   "
DRAW "   M-7,-25L3HL                             M-4,-8     "
DRAW "    M-2,-4U17                              M-3,-7     "
DRAW "     M+1,-4E2M-3,-7U8EUE4         BM130,81M+5,1R6     "
DRAW "    FR4FRF3D3GL3FL3M-4,-2G2D    L3HL2DFM+3,1R2L9H     "
DRAW "      GLEU2L3H3LHLU2E2RER2      M+5,-2BM165,93U2      "
DRAW "     M+1,-3E4   M+13,-2               RM+7,3D4G3      "
DRAW "       L3DLD3                             M-7,-1      "
DRAW "        M+5,-1L4                                      "
DRAW "         M+4,-1L3       EUHD    LD2L3                 "
DRAW "          M-3,-1UL      G2L4BM148,113                 "
DRAW "           M+1,4R5       F2R5M+4,-2                   "
DRAW "             R2EU5    M+1,2D7GDGLGL5H                 "
DRAW "             LM-5,-2       L4UHU5                     "
DRAW "              BM          154,128                     "
DRAW "               R3FRER2ER            F2RF2R            "
DRAW "                 DL4HL10HG       L3GL5UER             "
DRAW "                    EM+5,-1RBM147,133F3               "
DRAW "                        M+3,1R10E2RE                  "
DRAW "                          M-3,+6L13                   "
DRAW "                            M-3,-6                    "

PAINT (200, 50), 0, 0
PAINT (140, 85), 0, 0
PAINT (175, 85), 0, 0
PAINT (160, 120), 0, 0
PAINT (150, 130), 0, 0
PAINT (155, 139), 0, 0
