REM This is a very long line that would be split if it weren't in a comment. This comment uses the REM keyword, which the LineSplittingTextWriter needs to be able to detect. The following line uses a DATA statement to the same effect, and afterward this same comment is duplicated using a single tick comment.

DATA a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a% + a%

' This is a very long line that would be split if it weren't in a comment. This comment uses the REM keyword, which the LineSplittingTextWriter needs to be able to detect. The following line uses a DATA statement to the same effect, and afterward this same comment is duplicated using a single tick comment.


