PRINT "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc abcde"

PRINT "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" + "abc" +  _
"abc abcdef"

