using System;

namespace QBX.Platform.Windows;

[Flags]
public enum ConsoleInputModes
{
	ENABLE_PROCESSED_INPUT = 0x001,
	ENABLE_LINE_INPUT = 0x002,
	ENABLE_ECHO_INPUT = 0x004,
	ENABLE_WINDOW_INPUT = 0x008,
	ENABLE_MOUSE_INPUT = 0x010,
	ENABLE_INSERT_MODE = 0x020,
	ENABLE_QUICK_EDIT_MODE = 0x040,
	ENABLE_VIRTUAL_TERMINAL_INPUT = 0x200,
}
