using QBX.Hardware;
using QBX.Platform.Windows;

namespace QBX.Terminal.Platform.Windows;

public static class VirtualKeyCodesExtensions
{
	public static VirtualKeyCodes ToVirtualKeyCode(this SDL3.SDL.Scancode sdlScanCode)
	{
		switch (sdlScanCode)
		{
			case SDL3.SDL.Scancode.A: return VirtualKeyCodes.VK_A;
			case SDL3.SDL.Scancode.B: return VirtualKeyCodes.VK_B;
			case SDL3.SDL.Scancode.C: return VirtualKeyCodes.VK_C;
			case SDL3.SDL.Scancode.D: return VirtualKeyCodes.VK_D;
			case SDL3.SDL.Scancode.E: return VirtualKeyCodes.VK_E;
			case SDL3.SDL.Scancode.F: return VirtualKeyCodes.VK_F;
			case SDL3.SDL.Scancode.G: return VirtualKeyCodes.VK_G;
			case SDL3.SDL.Scancode.H: return VirtualKeyCodes.VK_H;
			case SDL3.SDL.Scancode.I: return VirtualKeyCodes.VK_I;
			case SDL3.SDL.Scancode.J: return VirtualKeyCodes.VK_J;
			case SDL3.SDL.Scancode.K: return VirtualKeyCodes.VK_K;
			case SDL3.SDL.Scancode.L: return VirtualKeyCodes.VK_L;
			case SDL3.SDL.Scancode.M: return VirtualKeyCodes.VK_M;
			case SDL3.SDL.Scancode.N: return VirtualKeyCodes.VK_N;
			case SDL3.SDL.Scancode.O: return VirtualKeyCodes.VK_O;
			case SDL3.SDL.Scancode.P: return VirtualKeyCodes.VK_P;
			case SDL3.SDL.Scancode.Q: return VirtualKeyCodes.VK_Q;
			case SDL3.SDL.Scancode.R: return VirtualKeyCodes.VK_R;
			case SDL3.SDL.Scancode.S: return VirtualKeyCodes.VK_S;
			case SDL3.SDL.Scancode.T: return VirtualKeyCodes.VK_T;
			case SDL3.SDL.Scancode.U: return VirtualKeyCodes.VK_U;
			case SDL3.SDL.Scancode.V: return VirtualKeyCodes.VK_V;
			case SDL3.SDL.Scancode.W: return VirtualKeyCodes.VK_W;
			case SDL3.SDL.Scancode.X: return VirtualKeyCodes.VK_X;
			case SDL3.SDL.Scancode.Y: return VirtualKeyCodes.VK_Y;
			case SDL3.SDL.Scancode.Z: return VirtualKeyCodes.VK_Z;
			case SDL3.SDL.Scancode.Alpha1: return VirtualKeyCodes.VK_1;
			case SDL3.SDL.Scancode.Alpha2: return VirtualKeyCodes.VK_2;
			case SDL3.SDL.Scancode.Alpha3: return VirtualKeyCodes.VK_3;
			case SDL3.SDL.Scancode.Alpha4: return VirtualKeyCodes.VK_4;
			case SDL3.SDL.Scancode.Alpha5: return VirtualKeyCodes.VK_5;
			case SDL3.SDL.Scancode.Alpha6: return VirtualKeyCodes.VK_6;
			case SDL3.SDL.Scancode.Alpha7: return VirtualKeyCodes.VK_7;
			case SDL3.SDL.Scancode.Alpha8: return VirtualKeyCodes.VK_8;
			case SDL3.SDL.Scancode.Alpha9: return VirtualKeyCodes.VK_9;
			case SDL3.SDL.Scancode.Alpha0: return VirtualKeyCodes.VK_0;
			case SDL3.SDL.Scancode.Return: return VirtualKeyCodes.VK_RETURN;
			case SDL3.SDL.Scancode.Escape: return VirtualKeyCodes.VK_ESCAPE;
			case SDL3.SDL.Scancode.Backspace: return VirtualKeyCodes.VK_BACK;
			case SDL3.SDL.Scancode.Tab: return VirtualKeyCodes.VK_TAB;
			case SDL3.SDL.Scancode.Space: return VirtualKeyCodes.VK_SPACE;
			case SDL3.SDL.Scancode.Minus: return VirtualKeyCodes.VK_OEM_MINUS;
			case SDL3.SDL.Scancode.Equals: return VirtualKeyCodes.VK_OEM_PLUS;
			case SDL3.SDL.Scancode.Leftbracket: return VirtualKeyCodes.VK_OEM_4;
			case SDL3.SDL.Scancode.Rightbracket: return VirtualKeyCodes.VK_OEM_6;
			case SDL3.SDL.Scancode.Backslash: return VirtualKeyCodes.VK_OEM_5;
			case SDL3.SDL.Scancode.NonUsHash: return VirtualKeyCodes.VK_OEM_5;
			case SDL3.SDL.Scancode.Semicolon: return VirtualKeyCodes.VK_OEM_1;
			case SDL3.SDL.Scancode.Apostrophe: return VirtualKeyCodes.VK_OEM_7;
			case SDL3.SDL.Scancode.Grave: return VirtualKeyCodes.VK_OEM_3;
			case SDL3.SDL.Scancode.Comma: return VirtualKeyCodes.VK_OEM_COMMA;
			case SDL3.SDL.Scancode.Period: return VirtualKeyCodes.VK_OEM_PERIOD;
			case SDL3.SDL.Scancode.Slash: return VirtualKeyCodes.VK_OEM_2;
			case SDL3.SDL.Scancode.Capslock: return VirtualKeyCodes.VK_CAPITAL;
			case SDL3.SDL.Scancode.F1: return VirtualKeyCodes.VK_F1;
			case SDL3.SDL.Scancode.F2: return VirtualKeyCodes.VK_F2;
			case SDL3.SDL.Scancode.F3: return VirtualKeyCodes.VK_F3;
			case SDL3.SDL.Scancode.F4: return VirtualKeyCodes.VK_F4;
			case SDL3.SDL.Scancode.F5: return VirtualKeyCodes.VK_F5;
			case SDL3.SDL.Scancode.F6: return VirtualKeyCodes.VK_F6;
			case SDL3.SDL.Scancode.F7: return VirtualKeyCodes.VK_F7;
			case SDL3.SDL.Scancode.F8: return VirtualKeyCodes.VK_F8;
			case SDL3.SDL.Scancode.F9: return VirtualKeyCodes.VK_F9;
			case SDL3.SDL.Scancode.F10: return VirtualKeyCodes.VK_F10;
			case SDL3.SDL.Scancode.F11: return VirtualKeyCodes.VK_F11;
			case SDL3.SDL.Scancode.F12: return VirtualKeyCodes.VK_F12;
			case SDL3.SDL.Scancode.Printscreen: return VirtualKeyCodes.VK_PRINT;
			case SDL3.SDL.Scancode.Scrolllock: return VirtualKeyCodes.VK_SCROLL;
			case SDL3.SDL.Scancode.Pause: return VirtualKeyCodes.VK_PAUSE;
			case SDL3.SDL.Scancode.Insert: return VirtualKeyCodes.VK_INSERT;
			case SDL3.SDL.Scancode.Home: return VirtualKeyCodes.VK_HOME;
			case SDL3.SDL.Scancode.Pageup: return VirtualKeyCodes.VK_PRIOR;
			case SDL3.SDL.Scancode.Delete: return VirtualKeyCodes.VK_DELETE;
			case SDL3.SDL.Scancode.End: return VirtualKeyCodes.VK_END;
			case SDL3.SDL.Scancode.Pagedown: return VirtualKeyCodes.VK_NEXT;
			case SDL3.SDL.Scancode.Right: return VirtualKeyCodes.VK_RIGHT;
			case SDL3.SDL.Scancode.Left: return VirtualKeyCodes.VK_LEFT;
			case SDL3.SDL.Scancode.Down: return VirtualKeyCodes.VK_DOWN;
			case SDL3.SDL.Scancode.Up: return VirtualKeyCodes.VK_UP;
			case SDL3.SDL.Scancode.NumLockClear: return VirtualKeyCodes.VK_NUMLOCK;
			case SDL3.SDL.Scancode.KpDivide: return VirtualKeyCodes.VK_DIVIDE;
			case SDL3.SDL.Scancode.KpMultiply: return VirtualKeyCodes.VK_MULTIPLY;
			case SDL3.SDL.Scancode.KpMinus: return VirtualKeyCodes.VK_SUBTRACT;
			case SDL3.SDL.Scancode.KpPlus: return VirtualKeyCodes.VK_ADD;
			case SDL3.SDL.Scancode.KpEnter: return VirtualKeyCodes.VK_RETURN;
			case SDL3.SDL.Scancode.Kp1: return VirtualKeyCodes.VK_NUMPAD1;
			case SDL3.SDL.Scancode.Kp2: return VirtualKeyCodes.VK_NUMPAD2;
			case SDL3.SDL.Scancode.Kp3: return VirtualKeyCodes.VK_NUMPAD3;
			case SDL3.SDL.Scancode.Kp4: return VirtualKeyCodes.VK_NUMPAD4;
			case SDL3.SDL.Scancode.Kp5: return VirtualKeyCodes.VK_NUMPAD5;
			case SDL3.SDL.Scancode.Kp6: return VirtualKeyCodes.VK_NUMPAD6;
			case SDL3.SDL.Scancode.Kp7: return VirtualKeyCodes.VK_NUMPAD7;
			case SDL3.SDL.Scancode.Kp8: return VirtualKeyCodes.VK_NUMPAD8;
			case SDL3.SDL.Scancode.Kp9: return VirtualKeyCodes.VK_NUMPAD9;
			case SDL3.SDL.Scancode.Kp0: return VirtualKeyCodes.VK_NUMPAD0;
			case SDL3.SDL.Scancode.KpPercent: return VirtualKeyCodes.VK_DECIMAL;
			case SDL3.SDL.Scancode.NonUsBackSlash: return VirtualKeyCodes.VK_OEM_3;
			case SDL3.SDL.Scancode.Application: return VirtualKeyCodes.VK_APPS;
			case SDL3.SDL.Scancode.KpEquals: return VirtualKeyCodes.VK_OEM_PLUS;
			case SDL3.SDL.Scancode.F13: return VirtualKeyCodes.VK_F13;
			case SDL3.SDL.Scancode.F14: return VirtualKeyCodes.VK_F14;
			case SDL3.SDL.Scancode.F15: return VirtualKeyCodes.VK_F15;
			case SDL3.SDL.Scancode.F16: return VirtualKeyCodes.VK_F16;
			case SDL3.SDL.Scancode.F17: return VirtualKeyCodes.VK_F17;
			case SDL3.SDL.Scancode.F18: return VirtualKeyCodes.VK_F18;
			case SDL3.SDL.Scancode.F19: return VirtualKeyCodes.VK_F19;
			case SDL3.SDL.Scancode.F20: return VirtualKeyCodes.VK_F20;
			case SDL3.SDL.Scancode.F21: return VirtualKeyCodes.VK_F21;
			case SDL3.SDL.Scancode.F22: return VirtualKeyCodes.VK_F22;
			case SDL3.SDL.Scancode.F23: return VirtualKeyCodes.VK_F23;
			case SDL3.SDL.Scancode.F24: return VirtualKeyCodes.VK_F24;
			case SDL3.SDL.Scancode.Execute: return VirtualKeyCodes.VK_EXECUTE;
			case SDL3.SDL.Scancode.Help: return VirtualKeyCodes.VK_HELP;
			case SDL3.SDL.Scancode.Select: return VirtualKeyCodes.VK_SELECT;
			case SDL3.SDL.Scancode.Copy: return VirtualKeyCodes.VK_OEM_COPY;
			case SDL3.SDL.Scancode.Mute: return VirtualKeyCodes.VK_VOLUME_MUTE;
			case SDL3.SDL.Scancode.VolumeUp: return VirtualKeyCodes.VK_VOLUME_UP;
			case SDL3.SDL.Scancode.VolumeDown: return VirtualKeyCodes.VK_VOLUME_DOWN;
			case SDL3.SDL.Scancode.KpComma: return VirtualKeyCodes.VK_OEM_COMMA;
			case SDL3.SDL.Scancode.KpEqualsAs400: return VirtualKeyCodes.VK_OEM_PLUS;
			case SDL3.SDL.Scancode.Lang1: return VirtualKeyCodes.VK_KANA; // formerly named VK_HANGUL
			case SDL3.SDL.Scancode.Lang2: return VirtualKeyCodes.VK_HANJA;
			case SDL3.SDL.Scancode.Lang3: return VirtualKeyCodes.VK_KANA;
			case SDL3.SDL.Scancode.Lang4: return VirtualKeyCodes.VK_KANA;
			case SDL3.SDL.Scancode.Cancel: return VirtualKeyCodes.VK_CANCEL;
			case SDL3.SDL.Scancode.Clear: return VirtualKeyCodes.VK_CLEAR;
			case SDL3.SDL.Scancode.Prior: return VirtualKeyCodes.VK_PRIOR;
			case SDL3.SDL.Scancode.Return2: return VirtualKeyCodes.VK_RETURN;
			case SDL3.SDL.Scancode.Separator: return VirtualKeyCodes.VK_SEPARATOR;
			case SDL3.SDL.Scancode.DecimalSeparator: return VirtualKeyCodes.VK_DECIMAL;
			case SDL3.SDL.Scancode.KpTab: return VirtualKeyCodes.VK_TAB;
			case SDL3.SDL.Scancode.KpBackspace: return VirtualKeyCodes.VK_BACK;
			case SDL3.SDL.Scancode.KpA: return VirtualKeyCodes.VK_A;
			case SDL3.SDL.Scancode.KpB: return VirtualKeyCodes.VK_B;
			case SDL3.SDL.Scancode.KpC: return VirtualKeyCodes.VK_C;
			case SDL3.SDL.Scancode.KpD: return VirtualKeyCodes.VK_D;
			case SDL3.SDL.Scancode.KpE: return VirtualKeyCodes.VK_E;
			case SDL3.SDL.Scancode.KpF: return VirtualKeyCodes.VK_F;
			case SDL3.SDL.Scancode.KpSpace: return VirtualKeyCodes.VK_SPACE;
			case SDL3.SDL.Scancode.KpClear: return VirtualKeyCodes.VK_CLEAR;
			case SDL3.SDL.Scancode.LCtrl: return VirtualKeyCodes.VK_CONTROL;
			case SDL3.SDL.Scancode.LShift: return VirtualKeyCodes.VK_SHIFT;
			case SDL3.SDL.Scancode.LAlt: return VirtualKeyCodes.VK_MENU;
			case SDL3.SDL.Scancode.LGUI: return VirtualKeyCodes.VK_LWIN;
			case SDL3.SDL.Scancode.RCtrl: return VirtualKeyCodes.VK_CONTROL;
			case SDL3.SDL.Scancode.RShift: return VirtualKeyCodes.VK_SHIFT;
			case SDL3.SDL.Scancode.RAlt: return VirtualKeyCodes.VK_RMENU;
			case SDL3.SDL.Scancode.RGUI: return VirtualKeyCodes.VK_RWIN;
			case SDL3.SDL.Scancode.Sleep: return VirtualKeyCodes.VK_SLEEP;
		}

		return 0;
	}
}
