namespace QBX.OperatingSystem.Globalization;

// Most of these are numerically just international telephone dialing codes.
public enum CountryCode
{
	[CultureName("en-US")] UnitedStates            =   1,
	[CultureName("fr-CA")] CanadianFrench          =   2,
	[CultureName("es-419")] LatinAmerica           =   3,
	[CultureName("en-CA")] CanadianEnglish         =   4,
	[CultureName("ru-RU")] Russia                  =   7,
	[CultureName("en-ZA")] SouthAfrica             =  27,
	[CultureName("el-GR")] Greece                  =  30,
	[CultureName("nl-NL")] Netherlands             =  31,
	[CultureName("fr-BE")] Belgium                 =  32,
	[CultureName("fr-FR")] France                  =  33,
	[CultureName("es-ES")] Spain                   =  34,
	[CultureName("hu-HU")] Hungary                 =  36,
	[CultureName("Lt-sr")] SerbiaYugoslavia        =  38,
	[CultureName("it-IT")] Italy                   =  39,
	[CultureName("ro-RO")] Romania                 =  40,
	[CultureName("fr-CH")] Switzerland             =  41,
	[CultureName("cs-CZ")] Czechoslovakia          =  42,
	[CultureName("de-AT")] Austria                 =  43,
	[CultureName("en-UK")] UnitedKingdom           =  44,
	[CultureName("da-DK")] Denmark                 =  45,
	[CultureName("sv-SE")] Sweden                  =  46,
	[CultureName("nb-NO")] Norway                  =  47,
	[CultureName("pl-PL")] Poland                  =  48,
	[CultureName("de-DE")] Germany                 =  49,
	[CultureName("es-MX")] Mexico                  =  52,
	[CultureName("es-AR")] Argentina               =  54,
	[CultureName("pt-BR")] Brazil                  =  55,
	[CultureName("es-CL")] Chile                   =  56,
	[CultureName("es-CO")] Colombia                =  57,
	[CultureName("es-VE")] Venezuela               =  58,
	[CultureName("ms-MY")] Malaysia                =  60,
	[CultureName("en-AU")] Australia               =  61,
	[CultureName("en-NZ")] NewZealand              =  64,
	[CultureName("zh-SG")] Singapore               =  65,
	[CultureName("ja-JP")] Japan                   =  81,
	[CultureName("ko-KR")] Korea                   =  82,
	[CultureName("zh-CN")] China                   =  86,
	[CultureName("tr-TR")] Turkey                  =  90,
	[CultureName("hi-IN")] India                   =  91,
	[CultureName("pt-PT")] Portugal                = 351,
	[CultureName("en-IE")] Ireland                 = 353,
	[CultureName("is-IS")] Iceland                 = 354,
	[CultureName("sq-AL")] Albania                 = 355,
	[CultureName("fi-FI")] Finland                 = 358,
	[CultureName("bg-BG")] Bulgaria                = 359,
	[CultureName("Lt-sr")] SerbiaMontenegro        = 381,
	[CultureName("hr-HR")] Croatia                 = 384,
	[CultureName("sl-SI")] Slovenia                = 386,
	[CultureName("bs-BA")] Bosnia                  = 387,
	[CultureName("mk-MK")] Macedonia               = 389,
	[CultureName("sk-SK")] Slovakia                = 421,
	[CultureName("es-EC")] Ecuador                 = 593,
	[CultureName("ar")]    AreaSouth               = 785,
	[CultureName("zh-HK")] HongKong                = 852,
	[CultureName("zh-TW")] Taiwan                  = 886,
	[CultureName("he-IL")] Israel                  = 972,
}
